server:
  port: 9001

spring:
  datasource:
    url: jdbc:h2:mem:testdb # http://localhost:9001/h2-console
    driver-class-name: org.h2.Driver
    username: salem_nabeel
    password: sn
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/