server:
  port: 9001

spring:
  datasource:
    url: jdbc:h2:mem:testdb # http://localhost:9001/h2-console
    driver-class-name: org.h2.Driver
    username: salem_nabeel
    password: sn
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: DEPARTMENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost