server:
  port: 9090

spring:
  application:
    name: service-administrator
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      discovery:
        ignored-services: service-administrator

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true