server:
  port: 9191

spring:
  application:
    name: gateway-service # zuul-proxy

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 30000
  routes:
    department-service:
      path: /department/**
      service-id: department-service
  ignored-services: "*"