server:
  port: 8662

spring:
  application:
    name: gateway-service # zuul-proxy

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    resource-service:
      path: /resource/**
      service-id: resource-service
      strip-prefix: true
    user-service:
      path: /user/**
      service-id: user-service
      strip-prefix: true
    department-service:
      path: /department/**
      service-id: department-service
      strip-prefix: true